---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(tidyr)
library(ggplot2)
library(plotly)
library(ggrepel)
# library(ggdark)
# library(ggtext)
# library(patchwork)
```

# Crops

```{r}
crops <- data.table::fread("~/github/tidytues/tidytuesday/data/2021/2021-01-19/crops.csv") 
```


```{r}
crops
```

```{r}
crops %>% 
  tidyr::pivot_longer(-SubCounty) %>% 
  tidyr::drop_na() %>% 
  group_by(name) %>% 
  mutate(total = sum(value)) %>% 
  ungroup() %>% 
  mutate(pc = value / total) %>% 
  ggplot(aes(x = name, y = pc, fill = SubCounty)) + 
  geom_col() 
  # scale_y_log10()
crops %>% 
  tidyr::pivot_longer(-SubCounty) %>% 
  tidyr::drop_na() %>% 
  group_by(SubCounty) %>% 
  mutate(total = sum(value)) %>% 
  ungroup() %>% 
  mutate(pc = value / total,
         name = factor(name,
                       levels = c("Farming",
                                  "Mango",
                                  "Avocado",
                                  "Cashew Nut",
                                  "Coconut",
                                  "Coffee",
                                  "Tea",
                                  "Citrus",
                                  "Khat (Miraa)",
                                  "Macadamia"))) %>% 
  ggplot(aes(x = SubCounty, y = pc, fill = name)) + 
  geom_col() +
  coord_flip()


crops %>% 
    tidyr::pivot_longer(-SubCounty) %>% 
    tidyr::drop_na() %>% 
    group_by(SubCounty) %>% 
    summarize(total = sum(value)) %>% arrange(-total) %>% top_n(10) -> top_counties

crops %>% 
  filter(SubCounty != "KENYA") %>% 
  tidyr::pivot_longer(-SubCounty) %>% 
  tidyr::drop_na() %>% 
  filter(SubCounty %in% top_counties$SubCounty) %>% 
  group_by(SubCounty) %>% 
  mutate(total = sum(value)) %>% 
  ungroup() %>% 
  mutate(pc = value / total,
         name = factor(name,
                       levels = c("Farming",
                                  "Mango",
                                  "Avocado",
                                  "Cashew Nut",
                                  "Coconut",
                                  "Coffee",
                                  "Tea",
                                  "Citrus",
                                  "Khat (Miraa)",
                                  "Macadamia"))) %>% 
  ggplot(aes(x = name, y = SubCounty)) + 
  geom_point(aes(size = pc, fill = pc),
             pch = 22) +
  scale_size(range = c(1, 20)) +
  theme_light() +
  theme(panel.grid = element_blank(),
        panel.grid.major.y = element_line(size = .3, linetype = 3))
```


# households

```{r}
households <- data.table::fread("~/github/tidytues/tidytuesday/data/2021/2021-01-19/households.csv")
```

```{r}
households
```

# gender

```{r}
gender <- data.table::fread("~/github/tidytues/tidytuesday/data/2021/2021-01-19/gender.csv")
```

```{r}
gender
```


# rKenyaCensus
```{r}
# install.packages("skimr")
# devtools::install_github("Shelmith-Kariuki/rKenyaCensus")
library("rKenyaCensus")
library(dplyr)
livestock <- rKenyaCensus::V4_T2.23 %>% data.table::as.data.table()
livestock[, County := as.factor(County)]
livestock[, SubCounty := as.factor(SubCounty)]
livestock[, AdminArea := as.factor(AdminArea)]

skimr::skim(livestock)
```

```{r}
ls <- livestock[AdminArea == "SubCounty"] %>% tidyr::drop_na()
ls

ls[, -1:-3] %>% prcomp(scale = TRUE, center = TRUE) -> pcafit

library(ggfortify)
autoplot(pcafit,
         data = ls,
         colour = "SubCounty",
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 3,
         ) -> p
ggplotly(p)
```

```{r}
ls <- livestock[AdminArea == "County"] %>% tidyr::drop_na()
ls %>% 
  select(-contains("Fish")) -> ls

ls[, -1:-3] %>% prcomp(scale = TRUE, center = TRUE) -> pcafit
library(ggdark)
library(ggfortify)
autoplot(pcafit,
         data = ls,
         colour = "County",
         # loadings = F,
         size = 1.6,
         label = T, #"County",
         label.label = "County",
         label.repel = TRUE,
         # label.colour = "forestgreen",
         label.size = 3,
         loadings.label.repel = TRUE,
         loadings.colour = 'gray30',
         loadings.label.colour = "gray30",
         loadings.label = TRUE,
         loadings.label.size = 3,
         loadings.label.hjust = 1
         ) +
  scale_x_continuous(breaks = 0) +
  scale_y_continuous(breaks = 0) +
  # theme_minimal() +
  dark_theme_minimal() +
  theme(legend.position = "none",
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = margin(20, 20, 20, 20),
        panel.grid.major.x = element_line(size = 0.3,
                                          linetype = 3,
                                          # arrow = grid::arrow(ends = "both", length = unit(4, "mm"), type = "closed"),
                                          colour = "gray90"),
        panel.grid.major.y = element_line(size = 0.3,
                                          linetype = 3,,
                                          # arrow = grid::arrow(ends = "both", length = unit(4, "mm")),
                                          colour = "gray90")) +
  coord_cartesian(ylim = c(-.6, .45)) +
  annotate(geom = "text",
           x = 0.56,
           y = 0.02,
           label = "1st Component",
           size = 3.5,
           color = "gray90"
           ) +
  annotate(geom = "text",
           x = -0.01,
           y = 0.4,
           label = "2nd Component",
           angle = 90,
           size = 3.5,
           color = "gray90"
           ) -> p1#-> p
  # theme_bw()+
  # theme(plot.background = element_rect(fill = "black"),
  #       panel.background = element_rect(fill = "black"))-> p
# ggplotly(p)

p1

ggplot(data = ls, 
       aes(x = forcats::fct_reorder(County, Farming),
                      y = Farming)) +
  geom_point() + 
  coord_flip() +
  dark_theme_minimal() +
  theme(legend.position = "none") -> p2
# ggplot(data = ls, aes(x = forcats::fct_reorder(County, Pigs),
#                       y = Pigs)) + 
#   geom_point() + coord_flip() -> p3
# ggplot(data = ls, aes(x = forcats::fct_reorder(County, Camels),
#                       y = Camels)) + 
#   geom_point() + coord_flip() -> p4
# ggplot(data = ls, aes(x = forcats::fct_reorder(County, Donkeys),
#                       y = Donkeys)) + 
#   geom_point() + coord_flip() -> p5
# 
# plotly::subplot(p2, p3, p4, p5, nrows = 2)

library(cowplot)

title <- ggtitle("A")

ggdraw(p1, xlim = c(0, 2)) +
  draw_plot(p2, scale = 0.75, x = 1) +
  theme(plot.background = element_rect(fill = "black"))
```


```{r}
# https://twitter.com/toeb18
# https://twitter.com/toeb18/status/1351976640256090119?s=20

library(sf)
shp <- st_as_sf(rKenyaCensus::KenyaCounties_SHP)

dat <- p1$data
dat$shade <- ifelse(dat$PC1 > 0, "Farming", "Desert")
st_as_sf(left_join(dat, shp, by = "County")) -> shp
ggplot(shp) + 
  geom_sf(aes(fill = PC1)) +
  geom_sf_label(aes(label = County), size = 2) + 
  dark_theme_light()-> p2

cowplot::plot_grid(p1, p2)
```

